<template>
  <div data-aos="fade" id="codeTyping"></div>
</template>

<script setup>
  import TypeIt from 'typeit';
  import { onMounted } from 'vue';

  onMounted(() => {
    new TypeIt("#codeTyping", {
    html: false,
    speed: 1,
    cursor: false,
    })
      .type('<section id="navbar">')
      .break()
      .type('　<nav ref="headerRef" class="fixed-top headroom navbar navbar-expand-lg navbar-dark custom-navbar">')
      .break()
      .type('　　<div class="container-fluid">')
      .break()
      .type('　　　<a class="navbar-brand d-inline-flex align-items-center" href="#home">')
      .break()
      .type('　　　　<i class="fa fa-paw"></i>')
      .break()
      .type('　　　　<span class="d-block d-lg-none d-xl-block">DoggoNest｜狗狗窩研究所</span>')
      .break()
      .type('　　　</a>')
      .break()
      .break()
      .type('　　　<button')
      .break()
      .type('　　　　class="navbar-toggler"')
      .break()
      .type('　　　　type="button"')
      .break()
      .type('　　　　data-bs-toggle="collapse"')
      .break()
      .type('　　　　data-bs-target="#navbarSupportedContent"')
      .break()
      .type('　　　　aria-controls="navbarSupportedContent"')
      .break()
      .type('　　　　aria-expanded="false"')
      .break()
      .type('　　　　aria-label="Toggle navigation"')
      .break()
      .type('　　　>')
      .break()
      .type('　　　　<span class="navbar-toggler-icon"></span>')
      .break()
      .type('　　　</button>')
      .break()
      .type('　　　<div class="collapse navbar-collapse" id="navbarSupportedContent">')
      .break()
      .type('　　　　<ul class="navbar-nav me-auto mb-2 mb-lg-0">')
      .break()
      .type('　　　　　<li class="nav-item">')
      .break()
      .type('　　　　　　<a class="nav-link" aria-current="page" href="#news"><i class="bi bi-newspaper"></i> 最新消息</a>')
      .break()
      .type('　　　　　</li>')
      .break()
      .break()
      .type('　　　　　<li class="nav-item dropdown">')
      .break()
      .type('　　　　　　<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">')
      .break()
      .type('　　　　　　　<i class="fa-solid fa-handshake-angle"></i> 業務範圍')
      .break()
      .type('　　　　　　</a>')
      .break()
      .type('　　　　　　<ul class="dropdown-menu">')
      .break()
      .type('　　　　　　　<li>')
      .break()
      .type('　　　　　　　　<a class="dropdown-item" href="#services"><i class="fa-solid fa-hand-holding-heart"></i> 服務項目</a>')
      .break()
      .type('　　　　　　　</li>')
      .break()
      .type('　　　　　　　<li>')
      .break()
      .type('　　　　　　　　<a class="dropdown-item" href="#products"><i class="fa-solid fa-box-open"></i> 產品列表</a>')
      .break()
      .type('　　　　　　　</li>')
      .break()
      .type('　　　　　　　<li>')
      .break()
      .type('　　　　　　　　<a class="dropdown-item" href="#test"><i class="fa-solid fa-paw"></i> 狗狗性格小測驗</a>')
      .break()
      .type('　　　　　　　</li>')
      .break()
      .type('　　　　　　</ul>')
      .break()
      .type('　　　　　</li>')
      .break()
      .type('　　　　　<li class="nav-item dropdown">')
      .break()
      .type('　　　　　　<a')
      .break()
      .type('　　　　　　　class="nav-link dropdown-toggle"')
      .break()
      .type('　　　　　　　href="#"')
      .break()
      .type('　　　　　　　role="button"')
      .break()
      .type('　　　　　　　data-bs-toggle="dropdown"')
      .break()
      .type('　　　　　　　aria-expanded="false"')
      .break()
      .type('　　　　　　>')
      .break()
      .type('　　　　　　　<i class="bi bi-question-circle-fill"></i> 認識我們')
      .break()
      .type('　　　　　　</a>')
      .break()
      .type('　　　　　　<ul class="dropdown-menu">')
      .break()
      .type('　　　　　　　<li>')
      .break()
      .type('　　　　　　　　<a class="dropdown-item" href="#aboutUs"><i class="bi bi-info-circle-fill"></i> 關於我們</a>')
      .break()
      .type('　　　　　　　</li>')
      .break()
      .type('　　　　　　　<li>')
      .break()
      .type('　　　　　　　　<a class="dropdown-item" href="#contact"><i class="bi bi-envelope-fill"></i> 聯絡我們</a>')
      .break()
      .type('　　　　　　　</li>')
      .break()
      .type('　　　　　　</ul>')
      .break()
      .type('　　　　　</li>')
      .break()
      .break()
      .type('　　　　　<li v-if="loginStatus" class="nav-item">')
      .break()
      .type('　　　　　　<a class="nav-link" aria-current="page" href="#"><i class="bi bi-person-circle"></i> 會員專區</a>')
      .break()
      .type('　　　　　</li>')
      .break()
      .type('　　　　</ul>')
      .break()
      .break()
      .type('　　　　<span class="float-end">')
      .break()
      .type('　　　　　<button')
      .break()
      .type('　　　　　　class="btn btn-match me-2"')
      .break()
      .type('　　　　　　data-bs-toggle="modal"')
      .break()
      .type('　　　　　　data-bs-target="#MatchModal"')
      .break()
      .type('　　　　　>')
      .break()
      .type('　　　　　　<i class="bi bi-person-raised-hand"></i>')
      .break()
      .type('　　　　　　認養流程')
      .break()
      .type('　　　　　</button>')
      .break()
      .go()
  })
  
</script>

<style scoped>
  #codeTyping {
    z-index: 0;
    position: absolute;
    font-size: 1em;
    font-family: 'Consolas';
    color: var(--bg);
    user-select: none;
    pointer-events: none;
    white-space: pre;

    height: 100%;
    width: 100%;
    background-color: var(--text);
  }
</style>